### PR TITLE
Add starter template for plugin. 

### PR DESCRIPTION
**Pull request by RajatVaryani**
This PR adds the starter template to the repository taken from https://github.com/mattermost/mattermost-plugin-starter-template

### CODE REVIEW

**Review by ilgooz — CHANGES_REQUESTED** [review]
Hey Rajat thanks! I think having only the `build` folder and `Makefile` is enough for our case.

If we use this whole starter template, we'll need to remove lots of things inside of it for ex. we don't need the webapp at all.

For the server part, I think what we're gonna do is will be similar to https://github.com/ilgooz/mattermost-plugin-topdf. I think we won't need to use server related code included to start template as well. Because only common code in the template is related to updating configurations but I plan to do something like [this](https://github.com/ilgooz/mattermost-plugin-topdf/blob/eb2480c/server/plugin.go#L55-L66) for that part.

Can you update this PR to reflect the changes please?

**Comment by RajatVaryani** [comment]
@ilgooz Let's setup a circleci pipeline as well.

**Review by ilgooz — CHANGES_REQUESTED** [review]
Thanks Rajat! Circleci is looking pretty good!

One last thing, can you please reset the _README_ file before merging?

You can put an empty _README_ with project's name for now and we can fill the rest out after the first implementation is done.

**Comment by RajatVaryani** [comment]
Done.

**Review by ilgooz — APPROVED** [review]
LGTM!

**Pull request merged**
